# Generated by Django 6.0.4 on 2026-04-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0002_alter_order_features_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='features',
            field=models.TextField(blank=True, default=list),
        ),
    ]
