# Generated by Django 6.0.4 on 2026-04-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0004_alter_offerdetail_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
